/* Nexa's demo provider is local. Replace requestDemoResponse with a fetch to a trusted
   same-origin /api/chat endpoint when a backend is available; never put API secrets here. */
(() => {
  'use strict';
  const STORAGE_KEY = 'nexa-ai.conversations.v1';
  const THEME_KEY = 'nexa-ai.theme';
  const $ = (selector, root = document) => root.querySelector(selector);
  const els = {list:$('#conversationList'),search:$('#searchInput'),title:$('#activeTitle'),scroll:$('#chatScroll'),messages:$('#messages'),welcome:$('#welcome'),input:$('#messageInput'),send:$('#sendButton'),composer:$('#composer'),dialog:$('#dialog'),dialogTitle:$('#dialogTitle'),dialogCopy:$('#dialogCopy'),dialogContent:$('#dialogContent'),dialogActions:$('#dialogActions'),toast:$('#toastRegion'),sidebar:$('#sidebar'),scrim:$('#scrim'),context:$('#contextMenu'),latest:$('#scrollLatest')};
  let state = loadState(), activeId = state.activeId, pending = false, lastQuery = '';
  let conversations = state.conversations;
  function uid(){ return globalThis.crypto?.randomUUID?.() || `c-${Date.now()}-${Math.random().toString(36).slice(2,9)}`; }
  function makeConversation(){const now=new Date().toISOString();return {id:uid(),title:'New conversation',messages:[],createdAt:now,updatedAt:now};}
  function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved&&Array.isArray(saved.conversations)){return {conversations:saved.conversations.filter(c=>c&&typeof c.id==='string'&&Array.isArray(c.messages)),activeId:saved.activeId};}}catch(e){console.warn('Nexa could not load saved conversations.');}return {conversations:[],activeId:null};}
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({conversations,activeId}));}catch(e){toast('Unable to save this conversation in browser storage.');}}
  function active(){return conversations.find(c=>c.id===activeId)||null;}
  function timestamp(){return new Date().toISOString();}
  function formatTime(date){return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(date));}
  function toast(message){const node=document.createElement('div');node.className='toast';node.textContent=message;els.toast.append(node);setTimeout(()=>node.remove(),2600);}
  function escapeHTML(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function renderInline(text){return escapeHTML(text).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');}
  // This renderer escapes every text fragment before using the limited generated markup below.
  function markdownHTML(source){
    const lines=String(source).replace(/\r/g,'').split('\n'),out=[];let paragraph=[],list=null,code=null,codeLines=[];
    const closeList=()=>{if(list){out.push(`</${list}>`);list=null;}};
    const flush=()=>{if(paragraph.length){out.push(`<p>${paragraph.map(renderInline).join('<br>')}</p>`);paragraph=[];}};
    for(const line of lines){const fence=line.match(/^\s*```([\w+-]*)\s*$/);if(fence){if(code===null){flush();closeList();code=fence[1]||'code';codeLines=[];}else{out.push(`<div class="code-wrap"><div class="code-head"><span>${escapeHTML(code)}</span><button class="code-copy" type="button" data-action="copy-code"><svg viewBox="0 0 24 24"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>Copy code</button></div><pre><code>${escapeHTML(codeLines.join('\n'))}</code></pre></div>`);code=null;}continue;}
      if(code!==null){codeLines.push(line);continue;}if(!line.trim()){flush();closeList();continue;}
      const bullet=line.match(/^\s*[-*]\s+(.+)/),number=line.match(/^\s*\d+[.)]\s+(.+)/);if(bullet||number){flush();const type=bullet?'ul':'ol';if(list!==type){closeList();list=type;out.push(`<${list}>`);}out.push(`<li>${renderInline((bullet||number)[1])}</li>`);continue;}closeList();paragraph.push(line);
    }
    if(code!==null)out.push(`<div class="code-wrap"><div class="code-head"><span>${escapeHTML(code)}</span><button class="code-copy" type="button" data-action="copy-code">Copy code</button></div><pre><code>${escapeHTML(codeLines.join('\n'))}</code></pre></div>`);flush();closeList();return out.join('');
  }
  const sparkSVG='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.5 14 10l6.5 2-6.5 2-2 6.5L10 14l-6.5-2 6.5-2 2-6.5Z"/><path d="m19 3 .7 2.3L22 6l-2.3.7L19 9l-.7-2.3L16 6l2.3-.7L19 3Z"/></svg>';
  function render(){const current=active();if(!current){const fresh=makeConversation();conversations.unshift(fresh);activeId=fresh.id;}
    const convo=active();els.title.textContent=convo.title;els.messages.replaceChildren();els.welcome.classList.toggle('hidden',convo.messages.length>0);convo.messages.forEach(message=>els.messages.append(renderMessage(message)));renderList();save();updateLatest();}
  function renderMessage(message){const isUser=message.role==='user',article=document.createElement('article');article.className=`message ${isUser?'user-message':'assistant-message'}`;article.dataset.messageId=message.id;
    const avatar=document.createElement('div');avatar.className=`message-avatar ${isUser?'user-avatar':'assistant-avatar'}`;avatar.setAttribute('aria-hidden','true');if(isUser)avatar.textContent='A';else avatar.innerHTML=sparkSVG;
    const body=document.createElement('div');body.className='message-body';const meta=document.createElement('div');meta.className='message-meta';const name=document.createElement('strong');name.textContent=isUser?'You':'Nexa';const time=document.createElement('span');time.className='message-time';time.textContent=formatTime(message.createdAt);meta.append(name,time);
    const content=document.createElement('div');content.className='message-content';if(isUser){content.textContent=message.content;}else content.innerHTML=markdownHTML(message.content);
    body.append(meta,content);const actions=document.createElement('div');actions.className='message-actions';actions.append(actionButton('copy','Copy','<svg viewBox="0 0 24 24"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>'));
    if(!isUser)actions.append(actionButton('regenerate','Regenerate','<svg viewBox="0 0 24 24"><path d="M20 7v5h-5M4 17v-5h5"/><path d="M5.6 9a7 7 0 0 1 11.8-2L20 12M4 12l2.6 5a7 7 0 0 0 11.8-2"/></svg>'));else actions.append(actionButton('edit','Edit','<svg viewBox="0 0 24 24"><path d="m14 5 5 5M4 20l4-.8L19 8a2.1 2.1 0 0 0-3-3L5 16l-1 4Z"/></svg>'));
    body.append(actions);if(isUser)article.append(body);else article.append(avatar,body);
    content.querySelectorAll('.code-copy').forEach(button=>button.addEventListener('click',()=>copyText(button.closest('.code-wrap').querySelector('code').textContent,button)));return article;
  }
  function actionButton(action,label,icon){const button=document.createElement('button');button.className='message-action';button.dataset.action=action;button.type='button';button.innerHTML=icon+`<span>${label}</span>`;return button;}
  function renderList(){const query=els.search.value.trim().toLowerCase();lastQuery=query;els.list.replaceChildren();const filtered=[...conversations].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).filter(c=>!query||c.title.toLowerCase().includes(query)||c.messages.some(m=>m.content.toLowerCase().includes(query)));
    if(!filtered.length){const empty=document.createElement('div');empty.className='no-results';empty.textContent=query?'No conversations found':'No conversations yet';els.list.append(empty);return;}
    filtered.forEach(convo=>{const row=document.createElement('div');row.className=`conversation-item ${convo.id===activeId?'active':''}`;const select=document.createElement('button');select.type='button';select.className='conversation-select';select.dataset.id=convo.id;select.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5v-15Z"/><path d="M4 20.5A2.5 2.5 0 0 1 6.5 18H20"/></svg>';const title=document.createElement('span');title.className='conversation-title';title.textContent=convo.title;select.append(title);select.addEventListener('click',()=>{activeId=convo.id;closeSidebar();render();});const more=document.createElement('button');more.type='button';more.className='conversation-more';more.setAttribute('aria-label',`Options for ${convo.title}`);more.dataset.menuId=convo.id;more.innerHTML='<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg>';row.append(select,more);els.list.append(row);});
  }
  function newChat(){const convo=makeConversation();conversations.unshift(convo);activeId=convo.id;els.search.value='';closeSidebar();render();els.input.focus();toast('New chat created');}
  function titleFrom(text){const clean=text.replace(/\s+/g,' ').trim();return clean.length>34?clean.slice(0,33).trimEnd()+'…':clean||'New conversation';}
  function addMessage(role,content){const convo=active();const message={id:uid(),role,content,createdAt:timestamp()};convo.messages.push(message);convo.updatedAt=message.createdAt;if(role==='user'&&convo.messages.filter(m=>m.role==='user').length===1&&convo.title==='New conversation')convo.title=titleFrom(content);save();return message;}
  function scrollToBottom(smooth=true){els.scroll.scrollTo({top:els.scroll.scrollHeight,behavior:smooth?'smooth':'auto'});}
  function updateLatest(){const away=els.scroll.scrollHeight-els.scroll.scrollTop-els.scroll.clientHeight>130;els.latest.classList.toggle('visible',away);}
  function showTyping(){const node=document.createElement('div');node.className='message assistant-message typing-message';node.innerHTML=`<div class="message-avatar assistant-avatar">${sparkSVG}</div><div class="message-body"><div class="message-meta"><strong>Nexa</strong><span class="message-time">now</span></div><div class="typing-dots" aria-label="Nexa is thinking"><i></i><i></i><i></i><span>Thinking</span></div></div>`;els.messages.append(node);scrollToBottom();return node;}
  async function requestDemoResponse(prompt){await new Promise(resolve=>setTimeout(resolve,700+Math.random()*500));const q=prompt.toLowerCase();
    if(/\b(html|javascript|css|code|program|debug|function|web development)\b/.test(q)){const topic=/\b(css)\b/.test(q)?'CSS':/\bhtml\b/.test(q)?'HTML':/\bjavascript\b/.test(q)?'JavaScript':'programming';return `A practical way to approach ${topic} is to make one small change at a time, then check what it does.\n\nFor a simple interactive page, separate the structure, presentation, and behavior:\n\n- **HTML** gives the page meaningful structure.\n- **CSS** controls spacing, type, and responsive layout.\n- **JavaScript** responds to user actions and updates the page.\n\n\`const button = document.querySelector('button');\`\n\nStart with a tiny working example, inspect it in the browser, and add complexity only when the basics feel clear. If you share the code or the exact behavior you want, I can help you work through it.`;}
    if(/\b(resume|cv|cover letter|job|interview)\b/.test(q))return `A strong career document makes the outcome of your work easy to see. Try this structure:\n\n1. Lead with a concise summary tailored to the role.\n2. Describe experience with action, scope, and result.\n3. Use specific numbers where you can support them.\n4. Mirror relevant language from the job description naturally.\n\nFor example: **“Improved the onboarding flow, reducing setup time by 20%.”**\n\nIf you share the role and a few details about your experience, I can help shape a focused draft.`;
    if(/\b(project|idea|build|portfolio)\b/.test(q))return `Here are a few approachable project directions with room to grow:\n\n- **Reading tracker:** save books, notes, and progress locally.\n- **Focus timer:** add short sessions, breaks, and a simple history.\n- **Neighborhood guide:** curate useful places with categories and search.\n\nChoose the one connected to a problem you actually care about. Define a first version that fits in a weekend, then add one thoughtful detail that makes it yours.`;
    if(/\b(email|write|draft|professional)\b/.test(q))return `Here is a clear starting point you can adapt:\n\n**Subject:** A quick follow-up\n\nHi [Name],\n\nI wanted to follow up about [specific topic]. [One sentence of context or your request.]\n\nWould [clear next step] work for you? I’m happy to share any other details that would be useful.\n\nBest,\n[Your name]\n\nKeep the request specific and adjust the tone to fit your relationship with the recipient.`;
    if(/\b(machine learning| ai |artificial intelligence|model)\b/.test(` ${q} `))return `Machine learning is a way for computers to find patterns in examples and use those patterns to make predictions.\n\nThink of showing a system many labeled photos of cats and dogs. It adjusts its internal settings until it can make a useful guess about a new photo. The examples it learns from matter a lot: biased or incomplete examples can lead to poor results.\n\nIn short: **examples in, learned pattern, prediction out.**`;
    if(/\b(plan|organize|priorit|manage|schedule)\b/.test(q))return `A lightweight plan can make this easier to act on:\n\n1. Write down the outcome you want.\n2. Break it into the next three concrete actions.\n3. Pick the smallest useful first step and give it a time.\n4. Leave space to review and adjust.\n\nIf you tell me your deadline and constraints, I can help turn this into a more specific plan.`;
    return `That’s a thoughtful question. A useful way to work through it is to clarify the outcome you want, identify what you already know, and separate assumptions from facts.\n\nFrom there, consider a couple of options and the trade-offs each one brings. If you share a little more context—such as your goal, constraints, or an example—I can give you a more specific answer.`;
  }
  async function generate(prompt,replaceId=null){if(pending)return;pending=true;els.send.disabled=true;const convo=active();const typing=showTyping();try{const response=await requestDemoResponse(prompt);typing.remove();if(replaceId){const index=convo.messages.findIndex(m=>m.id===replaceId);if(index>=0)convo.messages.splice(index,1);}addMessage('assistant',response);render();scrollToBottom();}catch(error){typing.remove();addMessage('assistant','Something went wrong while preparing a response. Please try again.');render();toast('Response unavailable. Please try again.');}finally{pending=false;updateSend();}}
  function send(content){const text=content.trim();if(!text||pending)return;addMessage('user',text);els.input.value='';resizeInput();render();scrollToBottom();generate(text);}
  function updateSend(){els.send.disabled=!els.input.value.trim()||pending;}
  function resizeInput(){els.input.style.height='auto';els.input.style.height=`${Math.min(els.input.scrollHeight,144)}px`;}
  async function copyText(text,button){try{await navigator.clipboard.writeText(text);}catch(e){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove();}if(button){const label=button.querySelector('span')||button;const old=label.textContent;label.textContent='Copied';setTimeout(()=>label.textContent=old,1200);}toast('Message copied');}
  function openDialog({title,copy,content,actions}){els.dialogTitle.textContent=title;els.dialogCopy.textContent=copy||'';els.dialogContent.replaceChildren();if(content)els.dialogContent.append(content);els.dialogActions.replaceChildren();actions.forEach(action=>{const b=document.createElement('button');b.type=action.submit?'submit':'button';b.className=`dialog-button ${action.kind||''}`;b.textContent=action.label;b.value=action.value||'';if(action.onClick)b.addEventListener('click',e=>{e.preventDefault();action.onClick();});els.dialogActions.append(b);});els.dialog.showModal();}
  function confirmDelete(id){const convo=conversations.find(c=>c.id===id);if(!convo)return;openDialog({title:'Delete conversation?',copy:`“${convo.title}” and its messages will be permanently removed from this browser.`,actions:[{label:'Cancel',value:'cancel'},{label:'Delete conversation',kind:'danger',onClick:()=>{conversations=conversations.filter(c=>c.id!==id);if(activeId===id){activeId=conversations[0]?.id||null;}els.dialog.close();render();toast('Conversation deleted');}}]});}
  function renameConversation(id){const convo=conversations.find(c=>c.id===id);if(!convo)return;const field=document.createElement('input');field.className='dialog-input';field.maxLength=60;field.value=convo.title;field.setAttribute('aria-label','Conversation title');openDialog({title:'Rename conversation',copy:'Choose a short, recognizable title.',content:field,actions:[{label:'Cancel',value:'cancel'},{label:'Save title',kind:'primary',onClick:()=>{const next=field.value.trim();if(next){convo.title=next;convo.updatedAt=timestamp();}els.dialog.close();render();}}]});field.focus();field.select();}
  function settings(){const content=document.createElement('div');const row=document.createElement('div');row.className='setting-row';row.innerHTML='<span>Appearance</span><span>';const theme=document.createElement('button');theme.className='dialog-button';theme.textContent=document.body.classList.contains('dark')?'Dark mode':'Light mode';theme.addEventListener('click',()=>{toggleTheme();theme.textContent=document.body.classList.contains('dark')?'Dark mode':'Light mode';});row.append(theme);content.append(row);const clear=document.createElement('button');clear.type='button';clear.className='dialog-button';clear.textContent='Clear all conversations';clear.style.marginTop='14px';clear.addEventListener('click',()=>confirmClear());content.append(clear);openDialog({title:'Settings',copy:'A few simple controls for your Nexa workspace.',content,actions:[{label:'Done',kind:'primary',value:'close'}]});}
  function confirmClear(){openDialog({title:'Clear all conversations?',copy:'Every saved conversation will be removed from this browser. This cannot be undone.',actions:[{label:'Cancel',value:'cancel'},{label:'Clear conversations',kind:'danger',onClick:()=>{conversations=[];activeId=null;els.dialog.close();render();toast('All conversations cleared');}}]});}
  function toggleTheme(){const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);localStorage.setItem(THEME_KEY,dark?'dark':'light');$('#themeState').textContent=dark?'Dark':'Light';document.querySelector('meta[name="theme-color"]').content=dark?'#17181c':'#f7f8fa';}
  function openSidebar(){els.sidebar.classList.add('open');els.scrim.classList.add('visible');$('#closeSidebar').focus();}
  function closeSidebar(){els.sidebar.classList.remove('open');els.scrim.classList.remove('visible');}
  function openContext(id,button){const rect=button.getBoundingClientRect();els.context.replaceChildren();[{text:'Rename',run:()=>renameConversation(id)},{text:'Delete',danger:true,run:()=>confirmDelete(id)}].forEach(item=>{const b=document.createElement('button');b.type='button';b.textContent=item.text;b.className=item.danger?'danger-text':'';b.setAttribute('role','menuitem');b.addEventListener('click',()=>{els.context.hidden=true;item.run();});els.context.append(b);});els.context.hidden=false;els.context.style.left=`${Math.min(rect.right-145,innerWidth-155)}px`;els.context.style.top=`${Math.min(rect.bottom+3,innerHeight-95)}px`;els.context.querySelector('button').focus();}
  els.composer.addEventListener('submit',e=>{e.preventDefault();send(els.input.value);});els.input.addEventListener('input',()=>{resizeInput();updateSend();});els.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!els.send.disabled)send(els.input.value);}});
  $('#newChat').addEventListener('click',newChat);$('#headerNew').addEventListener('click',newChat);$('#menuButton').addEventListener('click',openSidebar);$('#closeSidebar').addEventListener('click',closeSidebar);els.scrim.addEventListener('click',closeSidebar);$('#settingsButton').addEventListener('click',settings);$('#themeToggle').addEventListener('click',toggleTheme);els.search.addEventListener('input',renderList);els.latest.addEventListener('click',()=>scrollToBottom());els.scroll.addEventListener('scroll',updateLatest);
  $('#suggestions').addEventListener('click',e=>{const button=e.target.closest('[data-prompt]');if(button)send(button.dataset.prompt);});els.list.addEventListener('click',e=>{const button=e.target.closest('[data-menu-id]');if(button){e.stopPropagation();openContext(button.dataset.menuId,button);}});
  els.messages.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const article=button.closest('.message'),id=article.dataset.messageId,convo=active(),index=convo.messages.findIndex(m=>m.id===id),message=convo.messages[index];if(button.dataset.action==='copy')copyText(message.content,button);if(button.dataset.action==='edit'){els.input.value=message.content;resizeInput();updateSend();els.input.focus();convo.messages.splice(index);convo.updatedAt=timestamp();render();scrollToBottom();}if(button.dataset.action==='regenerate'){const prior=convo.messages.slice(0,index).reverse().find(m=>m.role==='user');if(prior)generate(prior.content,id);else toast('Send a message before regenerating.');}});
  document.addEventListener('click',e=>{if(!e.target.closest('.context-menu')&&!e.target.closest('[data-menu-id]'))els.context.hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape')els.context.hidden=true;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();newChat();}if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();els.search.focus();}});els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close();});
  try{if(localStorage.getItem(THEME_KEY)==='dark')document.body.classList.add('dark');}catch(e){}$('#themeState').textContent=document.body.classList.contains('dark')?'Dark':'Light';if(!conversations.length){const first=makeConversation();conversations.push(first);activeId=first.id;}else if(!conversations.some(c=>c.id===activeId))activeId=conversations[0].id;render();updateSend();
})();
